version: '3'

services:
  rustapache:
    build: .
    environment:
      - HTTP_DRIVER=apache
    volumes:
      - ./target/debug:/var/www/html/:z
      - ./storage:/var/www/html/storage/:z
    ports:
      - '80:80'
